fix #45959: AttributeError: 'NoneType' object has no attribute 'frame'
due to handling of __class__ when importing from living object (because
of missing source code or C-compiled object)

--HG--
branch : stable